Warning: closing unused connection 32 (<-localhost:11932) 

Warning: closing unused connection 31 (<-localhost:11932) 

Warning: closing unused connection 30 (<-localhost:11932) 

Warning: closing unused connection 29 (<-localhost:11932) 

Warning: closing unused connection 28 (<-localhost:11932) 

Error in checkForRemoteErrors(val) : 5 nodes produced errors; first error: object 'outperm1' not found 
